### ISSUE TITLE
Logging in with the correct credentials

### ISSUE THREAD

**Issue by AngelRam3** [JoshnaPR/ACME2-BI#1]
**As a** user
**I need** to be able to enter my username and password
**So that** I can enter the inventory tracking system

### Details and Assumptions
* I am a user with login credentials
* I am authorized to enter the inventory tracking system

### Acceptance Criteria
```gherkin
Given I am a user
When I enter my login credentials on the login page
Then I will authenticate my identity (2FA) and be allowed to access the inventory tracking system.

**Comment by JoshnaPR** [comment]
This has been completed.
